Homeworks to the Lectures on Pytest and on HTTP
SergiiButenko/GL_ProcampAuto_2020 pull request #5
Opened 2020-04-26 21:09 UTC by DennyL

Привет!

Проревьювь, пожалуйста, мои домашки.
По HTTP - в Lecture_3/Homework
По Pytest - в папке Lecture_Pytest.
Буду очень признателен за фидбэк.

2020-04-30 10:33 UTC, SergiiButenko requested changes
Fix issues

2020-04-30 10:33 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_3/Homework/homework_1.py
> +endpoints = ['', 'fail500', 'basic_auth']
'' - what is that?

2020-04-30 10:33 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_3/Homework/homework_1.py
> +    url = URL + endpoint
please take a look on URL join methods

2020-04-30 10:33 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_3/Homework/homework_1.py
> +        print('\nSending GET request to {}'.format(url))
use formatted string

2020-04-30 10:33 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_3/Homework/homework_2.py
> +            URL + 'items', json=item, headers={'Authorization': f'Bearer {access_token}'}
use var

2020-04-30 10:33 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_Pytest/homework/tests/test_suite.py
> +    assert len(testdata.access_token) > 0, "Token not received"
redo

2020-04-30 10:33 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_Pytest/homework/tests/test_suite.py
> +    assert 200 <= response_2.status_code < 300
raise_for_status

2020-05-07 17:08 UTC, DennyL commented on Denys_Lozinskyi/Lecture_3/Homework/homework_1.py
> +endpoints = ['', 'fail500', 'basic_auth']
Resolved in 6aaa4df commit

2020-05-07 17:09 UTC, DennyL commented on Denys_Lozinskyi/Lecture_3/Homework/homework_1.py
> +    url = URL + endpoint
Used urljoin lib. Resolved in 6aaa4df commit.

2020-05-07 17:11 UTC, DennyL commented on Denys_Lozinskyi/Lecture_3/Homework/homework_1.py
> +        print('\nSending GET request to {}'.format(url))
Taking full advantage of f-strings in 6aaa4df commit

2020-05-07 17:11 UTC, DennyL commented on Denys_Lozinskyi/Lecture_3/Homework/homework_2.py
> +            URL + 'items', json=item, headers={'Authorization': f'Bearer {access_token}'}
Done

2020-05-07 17:11 UTC, DennyL commented on Denys_Lozinskyi/Lecture_Pytest/homework/tests/test_suite.py
> +    assert len(testdata.access_token) > 0, "Token not received"
Done

2020-05-07 17:13 UTC, DennyL commented on Denys_Lozinskyi/Lecture_Pytest/homework/tests/test_suite.py
> +    assert 200 <= response_2.status_code < 300
Can't see how raise_for_status can be introduced into this particular case. Encapsulated the method instead.

2020-05-07 17:16 UTC, DennyL commented
Introduced all changes in 6aaa4df commit

2020-05-08 14:28 UTC, SergiiButenko approved these changes

2020-05-08 14:28 UTC, SergiiButenko commented on Denys_Lozinskyi/Lecture_Pytest/homework/config.py
> +base_url = 'http://0.0.0.0:5002'
should be upper case

2020-05-08 14:28 UTC, merged

2020-05-13 20:33 UTC, DennyL commented on Denys_Lozinskyi/Lecture_Pytest/homework/config.py
> +base_url = 'http://0.0.0.0:5002'
Done